#!/usr/bin/env python3
"""Generate kernel/symtab.c from the text symbols of a linked aos.elf.

Usage: gen_symtab.py <elf> <out.c>

Runs `nm -n` on the ELF and emits a sorted {addr,name} table for every
T/t (text) symbol in [0x00100000, 0x00400000) -- the kernel text range
(_end <= RAMDISK_BASE per linker.ld ASSERT). The generated file is compiled
and linked LAST so its presence never shifts the addresses being recorded.
"""
import subprocess
import sys

TEXT_LO = 0x00100000
TEXT_HI = 0x00400000


def main():
    if len(sys.argv) != 3:
        print("usage: gen_symtab.py <elf> <out.c>", file=sys.stderr)
        return 2
    elf, out = sys.argv[1], sys.argv[2]
    try:
        nm_out = subprocess.check_output(["nm", "-n", elf]).decode("utf-8", "replace")
    except subprocess.CalledProcessError:
        nm_out = ""
    entries = []
    for line in nm_out.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr_s, typ, name = parts
        if typ not in ("T", "t"):
            continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        if not (TEXT_LO <= addr < TEXT_HI):
            continue
        entries.append((addr, name))
    entries.sort()
    with open(out, "w") as f:
        f.write("/* generated by scripts/gen_symtab.py - do not edit */\n")
        f.write('#include "symtab.h"\n\n')
        f.write("const struct symtab_entry kernel_symtab[] = {\n")
        for addr, name in entries:
            f.write('    {0x%08x, "%s"},\n' % (addr, name))
        f.write("};\n")
        f.write("const unsigned int kernel_symtab_count = %d;\n" % len(entries))
    print("gen_symtab: %d text symbols -> %s" % (len(entries), out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
